apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: librsvg
  name: librsvg
spec:
  output:
    to:
      kind: ImageStreamTag
      name: librsvg:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/wusuopu/librsvg-api.git
    contextDir: /
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: librsvg:2.42.3-alpine
        namespace: wusuopu
type: Docker
